#!/bin/python3
# O. Bonaventure, 2019

from inginious import input, feedback, rst
import array
#q1 28 cipher suites
#q2 = www.computer-networking.info
#q3 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
# q4 Let's Encrypt
# q5 20-01-05

a1=int(input.get_input("q1"),10)
a2 = (input.get_input("q2")).lower().strip()
a3= (input.get_input("q3")).upper().strip()
a4= (input.get_input("q4")).upper().strip()
a5=(input.get_input("q5")).lower().strip()

grade=0


if(a1==28):
  feedback.set_problem_result("success","q1")
  grade+=20
  feedback.set_problem_feedback("Indeed, the client announces the ciphers that it supports in the Client Hello.","q1")
else:
  feedback.set_problem_result("failed","q1")
  feedback.set_problem_feedback("Check again the contents of the ClientHello.","q1") 


if(a2=="www.computer-networking.info"):
  feedback.set_problem_result("success","q2")
  grade+=20
  feedback.set_problem_feedback("Indeed, the client indicates the server name in the SNI extension.","q2")
else:
  feedback.set_problem_result("failed","q2")
  feedback.set_problem_feedback("Check again the contents of the ClientHello.","q2") 
  
if(a3=="TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"):
  feedback.set_problem_result("success","q3")
  grade+=20
  feedback.set_problem_feedback("Indeed, the server selects this cipher suite.","q3")
else:
  feedback.set_problem_result("failed","q1")
  feedback.set_problem_feedback("Check again the contents of the ServerHello.","q3") 



if("LET" in a4 and "ENCRYPT" in a4):
  feedback.set_problem_result("success","q4")
  grade+=20
  feedback.set_problem_feedback("Indeed, the certificate was issued by Let's Encrypt.","q4")
else:
  if("DIGITAL" in a4 or "TRUST" in a4):
    feedback.set_problem_result("failed","q4")
    feedback.set_problem_feedback("Do not confuse the certificate issued for the server and the certificate issued for the certification authority.","q4") 
  else:
    feedback.set_problem_result("failed","q4")
    feedback.set_problem_feedback("Check again the contents of the Certificate snet by the server.","q4") 

#20-01-05
l=a5.split('-')
if(len(l)!=3):    
  feedback.set_problem_result("failed","q5")
  feedback.set_problem_feedback("Please use the correct format.","q5")
else:
  if(int(l[0],10)==20 and int(l[1],10)==1 and int(l[2],10)==5):
    feedback.set_problem_result("success","q5")
    grade+=20
    
  
  
if(grade>=70):
  feedback.set_global_result("success")
else:
  feedback.set_global_result("failed")
      
feedback.set_grade(grade)
