#!/bin/python3
# O. Bonaventure, 2019

from inginious import input, feedback, rst
import array
#q1 server name = AM0PR0102CA0002.outlook.office365.com 
sname="AM0PR0102CA0002.outlook.office365.com".upper() 
#q2 = 3
a1 = (input.get_input("q1")).upper().strip()
a3= int(input.get_input("q3"),10)
grade=0


if(a1==sname):
  feedback.set_problem_result("success","q1")
  grade+=50
  feedback.set_problem_feedback("Indeed, the server announces its domain name as the first message in the SMTP session.","q1")

else:
  if(sname in a1):
    feedback.set_problem_result("failed","q1")
    feedback.set_problem_feedback("Your answer is not a fully qualified domain name. Check again the packet trace. In SMTP, the server announces its domain name in the first message that it sends in the SMTP session.", "q1")
  else:
    feedback.set_problem_result("failed","q1")
    feedback.set_problem_feedback("Check again the packet trace. In SMTP, the server announces its domain name in the first message that it sends in the SMTP session.", "q1")
  
if(a3==3):
  feedback.set_problem_result("success","q3")
  grade+=50
  feedback.set_problem_feedback("Indeed, the client sends the EHLO message, then STARTTLS and finally its ClientHello. Overall, it took 512 milliseconds to be able to transmit the first encrypted record.","q3")
else:
  feedback.set_problem_result("failed","q3")
  feedback.set_problem_feedback("Do not confuse a TCP acknowledgement from an SMTP command or a TLS record. The server messages are always originated from port 587 (the default port to submit SMTP messages) while the client port in this trace is 43540.","q3")

  
if(grade==100):
  feedback.set_global_result("success")
else:
  feedback.set_global_result("failed")
      
feedback.set_grade(grade)
